### ISSUE TITLE
Error when copying a sketch from P5.js into Mechanic

### ISSUE THREAD

**Issue by alelordelo** [designsystemsinternational/mechanic#112]
Thanks for such an elegant framework, can see how much passion you put into it! : )

**Goal:** 
Create a first tool test using an existing P5.js sketch.
https://p5js.org/examples/structure-width-and-height.html

**What I did:** 

Used the  Mechanic P5.js Video example, and replaced with a simple  P5.js Sketch 

```
export const handler = ({ inputs, mechanic, sketch }) => {
  const { width} =
    inputs;

    // Extract values of the inputs
    let angle = 0;


    //  Implementation of the design goes here

  sketch.setup = () => {
    sketch.createCanvas(width, height);
    };


  sketch.draw = () => {
    sketch.background("#F4F4F4");
    sketch.noStroke();

    for (let i = 0; i < height; i += 20) {
      fill(129, 206, 15);
      rect(0, i, width, 10);
      fill(255);
      rect(i, 0, 10, height);
    }

  };
};

export const inputs = {
  width: {
    type: "number",
    default: 400,
  },

};

export const presets = {
  medium: {
    width: 800,
  },

};

export const settings = {
  engine: require("@mechanic-design/engine-p5"),
  animated: true,
};
```

Problem:
I get an error "There was an error running the engine and/or function. Check the console!"

Is this the right approach to copy a sketch from P5.js into Mechanic? 

Cheers from Stockholm,
Alexandre

**Comment by fdoflorenzano** [comment]
Hey @alelordelo! Thanks for trying out Mechanic!

About the error, as the message suggested, did you check the console? That's where the actual error that appeared when trying to run the design function should appear. 

Looking at the code, looks like there's some stuff missing. You seem use undefined variables `height`, `rect`and `fill`, so I would guess that the function throws error when it gets to those. Note that usually p5 editors work in "global mode", while Mechanic's p5 is in instance mode and you should use the `sketch` argument to access p5 stuff. More about global and instance mode [here](https://github.com/processing/p5.js/wiki/Global-and-instance-mode).

So the approach should be right, but you still need to adapt a p5 sketch into Mechanic's environment and debug what the code tells you. I hope this helps!

**Comment by fdoflorenzano** [comment]
Due to inactivity, we'll be closing this issue. Feel free to re-open if you think this is really a Mechanic issue.
