### ISSUE TITLE
Bootstrap fails with .DS_Store files

### ISSUE THREAD

**Issue by bravomartin** [designsystemsinternational/mechanic#118]
**Describe the bug**
When I run `npm run bootstap` I get this error:

```
(node:91078) UnhandledPromiseRejectionWarning: Error: Cannot find module '/Users/bravomartin/WORK/DSI/mechanic/mechanic/packages/create-mechanic/function-examples/.DS_Store/dependencies.json'
```

**Expected behavior**
No Error

**Desktop (please complete the following information):**
 - OS: MacOs

**Additional context**
It looks like it's interpreting the `.DS_Store` file as a folder and wrongly assumes a `dependencies.json` file inside it.

**Comment by fdoflorenzano** [comment]
Good find!
