### ISSUE TITLE
Module 'immer' cannot be resolved

### ISSUE THREAD

**Issue by lnolte** [designsystemsinternational/mechanic#123]
**Describe the bug**
After generating a React-Image project from the CLI and starting the dev server, loading the page in the browser fails with an error on the command line:

```
ERROR in ./node_modules/use-immer/dist/use-immer.module.js 1:0-34
Module not found: Error: Can't resolve 'immer' in '~/projects/project-name/node_modules/use-immer/dist'
```

**To Reproduce**
1. Generate a project using `npm init mechanic@latest`
2. I chose the `React Image` template – haven't checked for other templates
3. Choose to install the dependencies – for me it used yarn
4. Start the dev server
5. Open `localhost:3000` and find the error on the command line

**Expected behavior**
The dev server should start normally, with all dependencies being in place.

**Desktop (please complete the following information):**
 - macOS 11.5.2
 - Chrome 100.0.4896.75

**Additional context**
Manually installing `immer` as a dependency solves the issue.

**Comment by lnolte** [comment]
Had a look at it again. Maybe this helps to narrow the issue down. I figured that skipping installation in the CLI and running `npm install` myself avoids the issue. The CLI would use `yarn` to install for me. 

I've also tried this using multiple node versions which makes the issue even weirder:
- node 17.7.1 (installing packages via CLI) ❌
- node 17.7.1 (installing packages myself) ✅
- node 16.4.0 (installing packages via CLI) ❌
- node 16.4.0 (installing packages myself) ✅
- node 14.15.0 (installing packages via CLI) ❌
- node 14.15.0 (installing packages myself) ❌

`npm list -g` does not include `immer` for any of the versions. Maybe this is also an issue with my node setup. I'll try on a different machine later and update the details accordingly.

**Comment by fdoflorenzano** [comment]
I think it may be a peer dependency issue. I believe yarn and different npm versions handle peer dependencies differently, and the issue here is that even tho `use-immer` is declared as a dependency, `immer` is not. I'll do a little release with this change. (I'll also include your latest PR)

**Comment by lnolte** [comment]
Yes, this solves it 😊

**Comment by fdoflorenzano** [comment]
Amazing 🎉
