### ISSUE TITLE
Image Upload with the react engine won't work 

### ISSUE THREAD

**Issue by kunaumadein** [designsystemsinternational/mechanic#130]
**Describe the bug**
To get a feel for the framework I had the Business Card Generator compiled as an example. I wanted to test something basic and add text and 2-3 images. But when I add an upload image input and reference it in react via <image> the image is displayed as broken.

**Expected behavior**
the uploaded Image should work as a background on the whole canvas.

**Desktop (please complete the following information):**
 - OS: [Mac OS]
 - Browser [Chrome]
<img width="1538" alt="Bildschirmfoto 2022-05-06 um 12 48 56" src="https://user-images.githubusercontent.com/105051395/167117878-94677a8c-f7d2-4f76-9bed-51b28e2d3339.png">

**Comment by fdoflorenzano** [comment]
Hi @kunaumadein ! Sorry for the delay answering. 

The image input it's a tricky one right now. The value it returns to the design function isn't something that can be used that directly, it's actually a [File Object](https://javascript.info/file) as that's the type of object that an HTML file input returns. 

There are ways of using that object though. In your case, for a React based function, you would need something like this:

```js
export const handler = ({ inputs, mechanic }) => {
  const {
    myImage,
  } = inputs;
  const [href, setHref] = useState("");

  useEffect(() => {
    if (myImage) {
      const reader = new FileReader();

      reader.onload = function () {
        setHref(reader.result);
      };

      reader.readAsDataURL(myImage);
    }
  }, []);
  
  return  <image href={href} />;
```

This is not the best, and we are aware of it, hopefully we refactor how this input works in the future. Although it's already possible to define your own input components, so maybe someone does it before!

I hope this helps!

**Comment by kunaumadein** [comment]
Thank you for the answer!
Ok I understand and I have implented the input function in my code and removed the inout definition above accordingly. But I still get an error message and that is useState("") is not defined. Currently i implemented this way:

```
import React, { useEffect } from "react";
import "./styles.css";

export const handler = ({ inputs, mechanic }) => {
  const {
    width,
    height,
    backgroundColor,
    colorOne,
    colorTwo,
    fontScale,
    company,
    name,
    email,
    email2,
    phone,
  } = inputs;

  const margin = width / 18;
  const fontSize = (width / 18) * fontScale;
  const textTop = margin + fontSize * 0.7;
  const lineHeight = fontSize * 1.2;

  const {
    myImage,
  } = inputs;
  const [href, setHref] = useState("");

  useEffect(() => {
    if (myImage) {
      const reader = new FileReader();

      reader.onload = function () {
        setHref(reader.result);
      };

      reader.readAsDataURL(myImage);
    }
  }, []);

  useEffect(() => {
    mechanic.done();
  }, []);
```

Thank you in advance!

<img width="917" alt="Bildschirmfoto 2022-05-09 um 09 15 04" src="https://user-images.githubusercontent.com/105051395/167359030-6ab5ab53-781e-40ce-a516-4da8e51c15c8.png">

**Comment by kunaumadein** [comment]
EDIT: I needed to import useState here:

```
import React, { useEffect, useState } from "react";
import "./styles.css";
```

Now it is working!

**Comment by fdoflorenzano** [comment]
Amazing! 🎉

**Comment by kunaumadein** [comment]
Helo it is me again!
I was just curious it it's possible to implement two image upload functions or is it currently limited to one image upload somehow? I wanted to import a logo in the top right corner and a logo in the bottom left corner.

**Comment by lnolte** [comment]
@kunaumadein sure, using the technique described by @fdoflorenzano you can add as many images as you'd like.

```javascript
import React, { useEffect, useState } from "react";

export const handler = ({ inputs, mechanic }) => {
  const { topLogo, bottomLogo } = inputs;
  const [topHref, setTopHref] = useState("");
  const [bottomHref, setBottomHref] = useState("");

  const loadImageFromFileObject = (fileObject, stateSetter) => {
    const reader = new FileReader();
    reader.onload = () => {
      stateSetter(reader.result);
    };
    reader.readAsDataURL(fileObject);
  };

  useEffect(() => {
    if (topLogo) loadImageFromFileObject(topLogo, setTopHref);
    if (bottomLogo) loadImageFromFileObject(bottomLogo, setBottomHref);

    mechanic.done();
  }, []);

  return (
    <svg width={400} height={400}>
      <image href={topHref} />
      <image href={bottomHref} />
    </svg>
  );
};

export const inputs = {
  topLogo: {
    type: "image",
    multiple: false,
  },
  bottomLogo: {
    type: "image",
    multiple: false,
  },
};

export const settings = {
  engine: require("@mechanic-design/engine-react"),
};
```

**Comment by kunaumadein** [comment]
ahh that's great. to rename the "hrefs" I also tried earlier but your variant is much better! Currently I have also built in a multiple export option so that I can output it as SVG or as PNG but it happens in the export that my 2 images that I retrieve through the filereader then do not appear in the PNG export. Only the background that I have currently imported and linked locally is displayed in the PNG export. Do I have to save the images from the retrieved filereader in between or something?

my current background which I imported from my machine:

```
import React, { useEffect, useState } from "react";
import ImgBanner from './assets/banner.svg';
import "./styles.css";
```

i return everything via: 
```
<image href={topHref}>
<image href={bottomHref}>
```

and after I hit export as PNG these to images will flicker for like 1 second and my final export is without the imported images.

**Comment by lnolte** [comment]
Interesting. So the way you've currently set it up `mechanic.done()` will be called everytime the component re-renders. Once an image is loaded this triggers a re-render, so that's why it's multiple downloads.

Normally state (where you store the hrefs) should be persisted between renders. So if it's working in the preview it should in theory also yield a working download. But exporting PNGs from SVG functions is a relatively new feature and I'm not fully aware of how it's implemented. I'll have a look at it later and get back to you :-)

**Comment by kunaumadein** [comment]
My solution with `mechanic.done()` is not final i was just curious on how it would behave. Importing different image types is of course working and stuff I am just confused why it won't download the uploaded images into my final PNG.

The method above where i put the `useEffect();` into the `mechanic.done();` behaves like that, that my first image that i upload will be downloaded into my final PNG file. If i trigger the second upload option then it will render that image in my final PNG.
So it is working but it will download 2 PNG files where one of them is without the uploaded images.

But thank you @lnolte for having a look :)

**Comment by lnolte** [comment]
@kunaumadein sorry it took a bit to get to this. I think there is some work for us to do, to make working with image uploads more straightforward. Thanks again so much for pointing this out 😊 

For now you should be able to get things working as expected by wrapping `mechanic.done()` in it's own `useEffect` with the loaded images being the dependencies.

```js
import React, { useEffect, useState } from "react";

export const handler = ({ inputs, mechanic }) => {
  const { topLogo, bottomLogo } = inputs;
  const [topHref, setTopHref] = useState("");
  const [bottomHref, setBottomHref] = useState("");

  const loadImageFromFileObject = (fileObject, stateSetter) => {
    const reader = new FileReader();
    reader.onload = () => {
      stateSetter(reader.result);
    };
    reader.readAsDataURL(fileObject);
  };

  useEffect(() => {
    if (topLogo) loadImageFromFileObject(topLogo, setTopHref);
    if (bottomLogo) loadImageFromFileObject(bottomLogo, setBottomHref);
  }, []);

  useEffect(() => {
    if (topHref && bottomHref) mechanic.done();
  }, [topHref, bottomHref]);

  return (
    <svg width={400} height={400}>
      <rect x={0} y={0} width={400} height={400} fill="black" />
      <image href={topHref} />
      <image href={bottomHref} />
    </svg>
  );
};

export const inputs = {
  topLogo: {
    type: "image",
    multiple: false,
  },
  bottomLogo: {
    type: "image",
    multiple: false,
  },
};

export const settings = {
  engine: require("@mechanic-design/engine-react"),
  showMultipleExports: true,
  optimize: false,
};
```

This will evaluate the second `useEffect` every time `topHref` or `bottomHref` changes, but only call `mechanic.done` if both have a value (so if both images have loaded).

**Comment by kunaumadein** [comment]
Hello @lnolte
I just implemented everything in my code and it works now! In each case the export of PNG files and SVG files is working fine right now.

My last question would be if the engine was updated somehow because i wanted to `npm run build` my project but somehow i will get the error message that my getStaticPath is not defined. But all the other commands will work like `npm run serve` for example.
![Uploading Bildschirmfoto 2022-05-16 um 12.35.54.png…]()


Thank you!

**Comment by fdoflorenzano** [comment]
@kunaumadein That error could be from a update we did in a recent release. Please report that last error in another issue, since it looks like another error not related to the original one reported in this issue. Make sure to check and report which version of mechanic you are using.

**Comment by kunaumadein** [comment]
@fdoflorenzano I see ok I will report it in another issue.
And thanks again for al the support with the image upload function!

**Comment by kunaumadein** [comment]
Hello @lnolte,
I tried to implement a little workaround and wanted to make sure, that i can upload 2 images or only 1 image and then export everything. Is it possible to say that I have my 2 image upload options but in a special use case the client will only upload one image and then wants to export the whole project with that single image he uploaded.

I tried to make something work with logical operators but everytime the mechanic.done(); function will be recalled several times and i will sometimes download 2 or 3 PNG files.

**Comment by kunaumadein** [comment]
@fdoflorenzano oh yeah sorry

My Code:

```
import React, { useEffect, useState } from "react";
import ImgBanner from './assets/banner.svg';
import "./styles.css";

export const handler = ({ inputs, mechanic }) => {
  const {
    subtitel,
    subtitel2,
    titel,
    titel2,
    untertitel,
    sponsoring,
  } = inputs;

  const { topLogo, bottomLogo } = inputs;
  const [topHref, setTopHref] = useState("");
  const [bottomHref, setBottomHref] = useState("");

  const loadImageFromFileObject = (fileObject, stateSetter) => {
    const reader = new FileReader();
    reader.onload = () => {
      stateSetter(reader.result);
    };
    reader.readAsDataURL(fileObject);
  };

  useEffect(() => {
    if (topLogo) loadImageFromFileObject(topLogo, setTopHref);
    if (bottomLogo) loadImageFromFileObject(bottomLogo, setBottomHref);
  }, []);

  useEffect(() => {
    if (topHref || bottomHref) mechanic.done();
 }, [topHref, bottomHref]);
```

The method with `if (topHref || bottomHref) mechanic.done();` i tried it before and when i import only one image i will work. But then lets assume i will upload 2 images then it will first download the PNG file with the image your uploaded first and then it will download the other PNG file with the 2 uploaded images.

**Comment by fdoflorenzano** [comment]
Gotcha, I was missing the rest of it. You get that because the readers change the state of the React component in different moments, so you get two calls to `mechanic.done`.

In a way, you need an extra validation to check that if there's an image waiting to be loaded, the function waits for it to load and to call `mechanic.done`. Maybe something like this is what you need:

```js
useEffect(() => {
    if ((topHref || bottomHref) && (!topLogo ||  topHref) && (!bottomLogo || bottomHref)) mechanic.done();
 }, [topLogo, topHref, bottomLogo,  bottomHref]);
``` 

Also @kunaumadein, at this point these questions are becoming more about React rendering more than about Mechanic. Please consider researching about React state and rendering, that could probably help you with some of these questions.

**Comment by kunaumadein** [comment]
I just tried your code and everything works!
Thank you again @fdoflorenzano 

And also realized that my questions are going more and more in the direction of react but my problem with the images you have solved wonderfully and therefore you could close the ticket at this point :)
