### ISSUE TITLE
Build App Function in version 2.0.0-beta.6 doesn't work after update

### ISSUE THREAD

**Issue by kunaumadein** [designsystemsinternational/mechanic#132]
**Describe the bug**
When i try to` npm run build` my current project I will get an ReferenceError: getStaticPath is not defined. 
Other commands like `npm run dev` and `npm run serve` work flawlessly.

Some weeks ago i tried to npm run build another project and it worked on version 2.0.0-beta.4

I put a screenshot with the whole message.

<img width="1036" alt="Bildschirmfoto 2022-05-16 um 12 35 54" src="https://user-images.githubusercontent.com/105051395/168664658-a9f601a2-4371-4e7b-8687-652c8830a313.png">

**Comment by fdoflorenzano** [comment]
@kunaumadein `2.0.0-beta.7`is out and should resolve this!

**Comment by kunaumadein** [comment]
@fdoflorenzano thanks I am gonna check i out!

**Comment by kunaumadein** [comment]
Ok updated everything and it is working @fdoflorenzano :)

**Comment by fdoflorenzano** [comment]
@kunaumadein great! I'm closing this issue then. Thanks again for the notice!
