### ISSUE TITLE
[v2.0.0-beta.9] Validation error when an input's type is changed and it conflicts with user's locally cached value

### ISSUE THREAD

**Issue by vpicone** [designsystemsinternational/mechanic#139]
### Describe the bug
If an input's type is changed to a less permissive type (ex. color → text with specified options) the local value cached in the user's browser will throw an error due to failed validation.

### To Reproduce
1. Publish a function with a color input
2. Navigate to the published function and make a selection for that input
3. Change the color input type to "text" with several options
4. Publish a new version of the function to the same domain
5. Navigate to the same function in the same browser
6. You'll see something like "MechanicError: Error is thrown during input X value validation: Supplied Input value (#fafafa) is not available in options: Red, Yellow, Green"

### Expected behavior
I expect a function to ignore users' stale values for an input when the type is changed

### Screenshots
![Screenshot of function throwing a MechanicError](https://user-images.githubusercontent.com/4078018/187828815-de36e74a-ad2f-468e-98ec-9054a7dadb0a.png)

### Desktop (please complete the following information):
 - OS: macOS Monteray
 - Browser: Chrome/Safari
 - Version: Latest

### Additional context
Changing the key value for the input avoids this scenario, but solutions like encoding the input type into the inputs name (themeText, themeColor) get cumbersome and are prone to mistakes.

Hashing individual input objects to create a unique ID (ala CSS modules) could be one way to ensure a stale value isn't used.

**Comment by runemadsen** [comment]
Hi @vpicone. Thanks so much for this! It's a known issue, and we just huddled to figure out the solution for it. Give us a few days and we'll try to get another release out. Until then, you can delete your `localStorage` items in the web developer console and it should reset the app back to its proper state.
