### ISSUE TITLE
create command with --template does not allow function names

### ISSUE THREAD

**Issue by puria** [designsystemsinternational/mechanic#165]
**Describe the bug**
When run `yarn new --template react-image my_design_function` the latest positional argument is not considered.
This creates always a function in `functions/react-image`

**To Reproduce**
1. create mechanic project
2. run `yarn new --template react-image my_design_function`

**Expected behavior**
I do expect to be able to pass a custom function design name ;p

**Comment by runemadsen** [comment]
Thanks! We can fix this on our end :)

**Comment by fdoflorenzano** [comment]
Hey there @puria ! Sorry for the delay, (and the auto-closing). We just merged a PR addresing this and we released version `v2.0.0-beta.10` where it should show reflected :)

Thanks again for reporting this!
