### ISSUE TITLE
Configuration of baseUrl

### ISSUE THREAD

**Issue by astrutz** [designsystemsinternational/mechanic#185]
**Is your feature request related to a problem? Please describe.**
When trying to deploy an mechanic app as an static html page under a specific path (e.g. https://mydomain.com/tools/function-name), I struggle because the generated files have paths which point to the root directory, e.g. https://mydomain.com/app-8j934fj.js.

**Describe the solution you'd like**
The mechanic.config.js has another field called baseUrl, which takes a path, in my case "/tools" and builds all files with that path in mind.

**Comment by fdoflorenzano** [comment]
Hey there! Thanks for reaching out.

We've encountered this before ourselves, and we've actually been using a key in config called `publicPath`, that I think is what you need/want.

Sorry for that hidden detail, it's on our to-do list to add more documentation around this.

**Comment by astrutz** [comment]
Hey, thank you very much for your help. Works like a treat!
