### ISSUE TITLE
To Do for v0.1.0 Release 

### ISSUE THREAD

**Issue by bravomartin** [designsystemsinternational/mechanic#19]
- [x] Replace all default exports
- [x] Establish engine through require statement, import not really necessary.
- [x] Remove size param and replace with params  and presets. width and height are not special. Must have defaults.
- [x] “Fast-preview” →  “Scale to fit” (Works only for design functions that draw relative to the canvas size)
- [x] Separate mechanic input components into own package, so that unnecessary code is not added but still user has the option to modify it if wants.
- [x] Unique number input, that has slider option that turns it into a slider ui. min, max, step.
- [x] on Select: "choices" → “Options”,  add option for  `{ value: label }` objects as well as the current array of strings.
- [x] Add a nice color picker input.
- [x] Being able to remember params. Use localstorage.
- [x] Add validation function option, and add the possibility to show errors. Return null if no error, or a string if error.
- [x] Check that randomization is working
- [x] Fix animation export

**Comment by fdoflorenzano** [comment]
Notes to self:

- [ ] Test new options declaration.
- [ ] Define a consistent way for mechanic to transform data types when returning values to df.
- [ ] Check CSS and search for now unused sections.
