### ISSUE TITLE
Deprecate Old Packages

### ISSUE THREAD

**Issue by bravomartin** [designsystemsinternational/mechanic#85]
Since we changed the scope of packages, all the old packages are [still around](https://www.npmjs.com/search?q=%40designsystemsinternational%2Fmechanic). 

It would be nice to push a deprecation message to the old packages (pointing at the new one) and then mark them as deprecated in npm.

**Comment by fdoflorenzano** [comment]
- [ ] [@designsystemsinternational/mechanic-engine-svg](https://www.npmjs.com/package/@designsystemsinternational/mechanic-engine-svg)
- [ ] [@designsystemsinternational/mechanic-engine-p5](https://www.npmjs.com/package/@designsystemsinternational/mechanic-engine-p5)
- [ ] [@designsystemsinternational/mechanic-engine-react](https://www.npmjs.com/package/@designsystemsinternational/mechanic-engine-react)
- [ ] [@designsystemsinternational/mechanic-engine-canvas](https://www.npmjs.com/package/@designsystemsinternational/mechanic-engine-canvas)
- [ ] [@designsystemsinternational/mechanic-cli](https://www.npmjs.com/package/@designsystemsinternational/mechanic-cli)
- [ ] [@designsystemsinternational/mechanic-fonts](https://www.npmjs.com/package/@designsystemsinternational/mechanic-fonts)
- [ ] [@designsystemsinternational/mechanic-utils](https://www.npmjs.com/package/@designsystemsinternational/mechanic-utils)
- [ ] [@designsystemsinternational/create-mechanic](https://www.npmjs.com/package/@designsystemsinternational/create-mechanic)
- [ ] [@designsystemsinternational/mechanic-ui-components](https://www.npmjs.com/package/@designsystemsinternational/mechanic-ui-components)
- [ ] [@designsystemsinternational/mechanic](https://www.npmjs.com/package/@designsystemsinternational/mechanic)

**Comment by fdoflorenzano** [comment]
@bravomartin Done! They no longer appear when searching [@designsystemsinternational](https://www.npmjs.com/search?q=%40designsystemsinternational) or [@designsystemsinternational/mechanic](https://www.npmjs.com/search?q=%40designsystemsinternational%2Fmechanic). :)

**Comment by bravomartin** [comment]
✨✨
